### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by lestrobl** [igormukhingmailcom/ajax-systems-api#1]
PHP Fatal error:  Uncaught Error: Class 'Mukhin\AjaxSystemsApi\Exception\AuthenticationException' not found in C:\xampp\htdocs\Ajax\src\AjaxSystemsApiClient.php:69
Stack trace:
#0 C:\xampp\htdocs\Ajax\examples\hubs\index.php(12): Mukhin\AjaxSystemsApi\AjaxSystemsApiClient->login('XXXXX', 'XXXXX')
#1 {main}
  thrown in C:\xampp\htdocs\Ajax\src\AjaxSystemsApiClient.php on line 69

Fatal error: Uncaught Error: Class 'Mukhin\AjaxSystemsApi\Exception\AuthenticationException' not found in C:\xampp\htdocs\Ajax\src\AjaxSystemsApiClient.php:69
Stack trace:
#0 C:\xampp\htdocs\Ajax\examples\hubs\index.php(12): Mukhin\AjaxSystemsApi\AjaxSystemsApiClient->login('XXXXX', 'xXXXX)
#1 {main}
  thrown in C:\xampp\htdocs\Ajax\src\AjaxSystemsApiClient.php on line 69

**Comment by igormukhingmailcom** [comment]
Sorry, but Ajax Systems removed web version of their app. 
So we no longer have ability to communicate with app.ajax.systems Web API (and this library is not useful anymore).
I will add notice at the to of this repo.
